baseURL = 'https://dubell.io/Dojo'
languageCode = 'en-us'
title = 'The Security Dōjō'
theme = "thedojo"

[markup]
    [markup.highlight]
        style = 'pygments'
        codeFences = true
        guessSyntax = false
        hl_Lines = ""
        lineNoStart = 1
        lineNos = true
        lineNumbersInTable = true
        tabWidth = 4

    [markup.tableOfContents]
        endLevel = 4
        ordered = true
        startLevel = 2
